apiVersion: v1
kind: Service
metadata:
  name: {{ include "RideSaver_Mock_Lyft.fullname" . }}
  labels:
    {{- include "RideSaver_Mock_Lyft.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{ range $index, $port := .Values.service.port }}
    - port: {{ $port.port }}
      targetPort: {{ $index }}
      protocol: TCP
      name: {{ default $index $port.name }}
    {{ end }}
  selector:
    {{- include "RideSaver_Mock_Lyft.selectorLabels" . | nindent 4 }}
